In [1]:
import math
import numpy as np
import seaborn as sns

# Matriz de pesos - 1a. capa

In [2]:
w1 = np.array([
[-19.2681157801412,2.27249901351911],
[4.80938896274739,-0.082558439782315],
[-24.1131845072106,1.21140367473092],
[118.681517016918,-3.92258307338915]
])

In [3]:
w2 = np.array([
[-1.15225220299697,-23.9015113364388,0.486311052226944],
[0.504567530636415,-18.0324122222704,-476.404089869933],
[-0.512662625454625,221.657324246666,0.18996302794802]
])

In [4]:
w3 = np.array([
[0.000474155890345046,0.585009107410016,0.430229281036369],
[-0.00140877024434706,-1.7517867821674,1.70641513303126],
[-6.39258019657287e-05,0.90011822826787,-0.902139385069451],
[1.50891586591292,-1.81939568843917,0.301206998960122]
])

In [13]:
def f_act(X):
    activada = []
    for x in X:
        try: 
            r = 1 / (1 + math.exp(-x))
        except OverflowError:
            r = 0
        activada.append(r)
    return np.array(activada)

In [14]:
#Carga de datos
iris =sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
xcols = ['sepal_length','sepal_width','petal_length','petal_width']
especie = iris['species'].unique()
especie

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [16]:
X = iris[xcols].copy()
X.insert(0,'bias',1)
X

     bias  sepal_length  sepal_width  petal_length  petal_width
0       1           5.1          3.5           1.4          0.2
1       1           4.9          3.0           1.4          0.2
2       1           4.7          3.2           1.3          0.2
3       1           4.6          3.1           1.5          0.2
4       1           5.0          3.6           1.4          0.2
..    ...           ...          ...           ...          ...
145     1           6.7          3.0           5.2          2.3
146     1           6.3          2.5           5.0          1.9
147     1           6.5          3.0           5.2          2.0
148     1           6.2          3.4           5.4          2.3
149     1           5.9          3.0           5.1          1.8

[150 rows x 5 columns]

In [17]:
#Prediccion 
prediccion = []
for index, fila in X.iterrows():
    capa1 = f_act(fila.dot(w1))
    capa1 = np.insert(capa1,0,1)
    capa2 = f_act(capa1.dot(w2))
    capa2 = np.insert(capa2,0,1)
    salida = f_act(capa2.dot(w3))
    prediccion.append(especie[np.argmax(salida)])

Exception: Dot product shape mismatch, (5,) vs (4, 2)

In [12]:
iris['Prediccion'] = prediccion
iris.head()

ValueError: Length of values (0) does not match length of index (150)